---
title: "Untitled"
author: "Smriti karki"
date: "11/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(haven)
library(tidyverse)
library(pagedown)
library(kableExtra)
library(dplyr)
```

```{r}
adae <- read_sas("E:/Numeric mind/adam/New_Study-master/New_Study-master/adam/adae.sas7bdat",NULL)
list <- adae %>%
  filter(SAFFL == "Y" &  APHASEN > 1 & AEWD == "Y" | AEACN == "DRUG WITHDRAWN") %>%
  select(SITEID,USUBJID,LTSUBJID,SAFFL,TRT01A,TRT01AN,AEOUT,ASTDTC,APHASE,AENDTC,ADURC,APHASEN,AGE,SEX,RACE,AESER,AEREL,AEWD,AEACN,AETERM,AEDECOD,AFTRTSTC,ALTRTSTC,ATTRTSTC,AETOX,ALAT,DRUG) %>% rename("Treatment"= TRT01A) %>% 
  arrange(USUBJID) %>% 
  unite("Site Id. / Unique Subject Id.",SITEID:USUBJID, sep = "/") %>% 
  mutate(SEX = case_when(
    SEX == "M" ~ "Male")) 
list <- list %>%  unite("Age (YEARS) / Sex/ Race",AGE:SEX:RACE, sep = "/") %>% 
  mutate(`Age (YEARS) / Sex/ Race`= case_when(
    duplicated(`Age (YEARS) / Sex/ Race`)==T ~ " ",
               TRUE ~ `Age (YEARS) / Sex/ Race`))
list <- list %>% 
  mutate(`Site Id. / Unique Subject Id.`=case_when(
    duplicated(`Site Id. / Unique Subject Id.`)==TRUE~" ",
    TRUE~`Site Id. / Unique Subject Id.`))
list <- list %>% 
  unite("Preferred Term/ VERBATIM TEXT",AEDECOD:AETERM,sep = "/") %>% 
  mutate(`Preferred Term/ VERBATIM TEXT` = case_when(
    duplicated(`Preferred Term/ VERBATIM TEXT`)==T ~ "",
    TRUE ~ `Preferred Term/ VERBATIM TEXT`))

list <- list %>% 
  unite("Outcome/ Onset Date/ Phase/ Date of Resolution/ Duration",AEOUT:ASTDTC:APHASE:AENDTC:ADURC, sep = "/") 
list <- list %>% 
  unite("Time Since 1st Dose/ Time Since Last Dose/ Time Since Phase Start", AFTRTSTC:ALTRTSTC:ATTRTSTC, sep = "/") %>% 
  unite("Side/Drug",ALAT:DRUG, sep = "/")
list <- list %>% 
   mutate(AEREL = case_when(
     AEREL == "Y" ~ "Yes")) %>% 
  mutate("Action Taken/ Relation to Study Treatment"=paste(AEACN,AEREL,sep = "/"))
list <- list %>% 
  mutate(AESER= case_when(
    AESER == "N" ~ "No")) %>% 
  mutate("Intensity or Maximum Grade/ Serious/ Withdrawal"= paste(AETOX,AESER,AEWD,sep = "/"))

list18 <- list %>% select(Treatment,`Site Id. / Unique Subject Id.`,`Age (YEARS) / Sex/ Race`,`Preferred Term/ VERBATIM TEXT`,`Outcome/ Onset Date/ Phase/ Date of Resolution/ Duration`,`Time Since 1st Dose/ Time Since Last Dose/ Time Since Phase Start`,`Intensity or Maximum Grade/ Serious/ Withdrawal`,`Action Taken/ Relation to Study Treatment`,`Side/Drug`)

title <- c("Listing 18 <br/>Listing of Adverse Events Leading to Withdrawal/Permanent Discontinuation of Investigational Product<br/> <br/>"=9 )
sidetitle <- c("Protocol: 209035 POLAR <br/>
Population: Safety<br/>"=9) 
footer <- paste("<br/><br/>","smritikarki:",getwd(),toupper(format(Sys.time(),format = "%d%b%Y %H:%M")))
kableExtra::kable(list18,align = "l",escape = F, bootstrap_options = "basic") %>% 
  kable_minimal(full_width = T, html_font = "Courier New") %>% 
  kableExtra::add_header_above(header = title,escape = F,line = F) %>% 
  kableExtra::add_header_above(header = sidetitle,escape = F,line = F,align = "l")
rm(list = ls()) 

                                       

```

