---
title: "Untitled"
author: "Smriti karki"
date: "10/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```
```{r}
adsl <- read_sas("E:/Numeric mind/adam/New_Study-master/New_Study-master/adam/adsl.sas7bdat",NULL)
test <- adsl %>% 
  select(COUNTRY,INVNAM,SITEID,TRT01P,TRT01PN) %>% 
  group_by(COUNTRY,SITEID,INVNAM,TRT01P) %>% 
  summarise(n = n())
test <- test %>% pivot_wider(names_from = TRT01P, values_from = n)
test$`DTG + RPV`[is.na(test$`DTG + RPV`)] <- 0
test$Q2M[is.na(test$Q2M)] <-0
test$`Not Assigned`[is.na(test$`Not Assigned`)]  <- 0
test <- test %>% mutate(Total = `DTG + RPV` +  Q2M + `Not Assigned`)
x <- sum(test$`DTG + RPV`)
y <- sum(test$Q2M)
z <- sum(test$`Not Assigned`)
t <- sum(test$Total)
test <- test %>%
  mutate(dtg = scales::percent(`DTG + RPV`/ x)) %>% 
  mutate(q2m = scales::percent(Q2M/y)) %>% 
  mutate(notassign = scales::percent(`Not Assigned`/z)) %>% 
  mutate(total = scales::percent(Total/t))
test$dtg <- assertive.base::parenthesise(test$dtg)
test$q2m <- assertive.base::parenthesise(test$q2m)
test$notassign <- assertive.base::parenthesise(test$notassign)
test$total <- assertive.base::parenthesise(test$total)
test <- test %>% 
  unite("DTG + RPV", c(`DTG + RPV`, dtg),  sep = "  ") %>% 
  unite("Q2M", c(Q2M,q2m),sep = "  ") %>% 
  unite("Not Assigned", c(`Not Assigned`,notassign),sep = "  ") %>% 
  unite("Total", c(Total,total),sep = "  ")
test <- test %>% 
  rename("Country "= COUNTRY)%>%
  rename("Investigator Name "= INVNAM) %>% 
  rename("Site Id."= SITEID)
test <- test %>%rename("Not Assigned
                         (N=1)"=`Not Assigned`)%>% 
                    rename("Q2M
                          (N=90)"=Q2M) %>%
                          rename("DTG + RPV
                                 (N=7)"="DTG + RPV") %>%
                           rename("Total
                                 (N=98)"=Total)
                                 
title <- c("Table 1.04 <br/>Summary of Number of Subjects Enrolled by Country and Site ID<br/> <br/>"=7 )
sidetitle <- c("Protocol: 209035 POLAR <br/>
Population: Enrolled<br/>"=7) 
footer <- paste("<br/><br/>","smritikarki:",getwd(),toupper(format(Sys.time(),format = "%d%b%Y %H:%M")))
kableExtra::kable(test,align = "l",escape = F, bootstrap_options = "basic") %>% 
  kable_minimal(full_width = T, html_font = "Courier New") %>% 
  kableExtra::add_header_above(header = title,escape = F,line = F) %>% 
  kableExtra::add_header_above(header = sidetitle,escape = F,line = F,align = "l")
rm(list = ls())                                  

```
